CREATE TABLE CUSTOMER(
   ID INT NOT NULL,
   NAME VARCHAR(100) NOT NULL,
   CONTACT VARCHAR(10),
   EMAIL VARCHAR(20),
   PRIMARY KEY(ID)
);

CREATE TABLE STAFF(
  ID INT NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  CONTACT VARCHAR(10),
  EMAIL VARCHAR(20),
  TYPE VARCHAR(20),
  PRIMARY KEY(ID)
);


