CREATE TABLE CUSTOMER(
   ID INT NOT NULL,
   NAME VARCHAR(100) NOT NULL,
   CONTACT VARCHAR(10) NOT NULL,  
   EMAIL VARCHAR(50),
   PRIMARY KEY(ID)
);

CREATE TABLE STAFF(
  ID INT NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  CONTACT VARCHAR(10) NOT NULL, 
  EMAIL VARCHAR(50),
  TYPE VARCHAR(20) NOT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE ADDRESS(
  ID INT NOT NULL,
  APARTMENT VARCHAR(100),
  STREET VARCHAR(100),
  CITY VARCHAR(100),
  ZIP INT NOT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE MENU(
   ID INT NOT NULL,
   NAME VARCHAR(100) NOT NULL,
   COST NUMBER NOT NULL,
   DESCRIPTION VARCHAR(100),
   PRIMARY KEY(ID)
);

CREATE TABLE ITEM(
   ID INT NOT NULL,
   NAME VARCHAR(100) NOT NULL,
   TYPE VARCHAR(20) NOT NULL,
   CATEGORY VARCHAR(20) NOT NULL,
   COST NUMBER NOT NULL,
   PRIMARY KEY(ID)
);

CREATE TABLE MENU_ITEM(
   MENU_ID NOT NULL,
   ITEM_ID NOT NULL,
   QUANTITY INT DEFAULT 0,
   FOREIGN KEY(MENU_ID) REFERENCES MENU(ID),
   FOREIGN KEY(ITEM_ID) REFERENCES ITEM(ID)
);

CREATE TABLE TYPE_DATA(
  ID INT NOT NULL,
  DESCRIPTION VARCHAR(100),
  PRIMARY KEY(ID)
);

CREATE TABLE ITEM_TYPE(
  ITEM_ID INT NOT NULL,
  TYPE_ID INT NOT NULL,
  FOREIGN KEY(ITEM_ID) REFERENCES ITEM(ID),
  FOREIGN KEY(TYPE_ID) REFERENCES TYPE_DATA(ID)
);

CREATE TABLE EVENT(
  ID INT NOT NULL,
  PEOPLE_COUNT INT NOT NULL,
  STAFF_COUNT INT NOT NULL,
  CUSTOMER_ID INT NOT NULL,
  ADDRESS_ID INT NOT NULL,
  MENU_ID INT NOT NULL,
  EXPECTED_DURATION INT NOT NULL, 
  ACTUAL_DURATION INT, 
  EVENT_DATE DATE NOT NULL,
  PRIMARY KEY(ID),
  FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(ID),
  FOREIGN KEY(ADDRESS_ID) REFERENCES ADDRESS(ID),
  FOREIGN KEY(MENU_ID) REFERENCES MENU(ID)
);


CREATE TABLE STAFF_BOOKING(
  STAFF_ID INT NOT NULL, 
  EVENT_ID INT NOT NULL,
  PAY_RATE NUMBER DEFAULT 10,
  HOURS_WORKED NUMBER DEFAULT 0,
  FOREIGN KEY(STAFF_ID) REFERENCES STAFF(ID),
  FOREIGN KEY(EVENT_ID) REFERENCES EVENT(ID)
);

-- DROP TABLE QUERIES IF REQUIRED
DROP TABLE CUSTOMER;
DROP TABLE STAFF;
DROP TABLE ADDRESS;
DROP TABLE MENU;
DROP TABLE ITEM;
DROP TABLE MENU_ITEM;
DROP TABLE TYPE_DATA;
DROP TABLE ITEM_TYPE;
DROP TABLE EVENT;
DROP TABLE STAFF_BOOKING;
