CREATE TABLE STAFF_AUDIT(
  ID INT NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  CONTACT VARCHAR(10),
  EMAIL VARCHAR(50),
  TYPE VARCHAR(20),
  OPERATION VARCHAR2(10) CHECK( operation IN('INSERT','UPDATE','DELETE')) NOT NULL,
  UPDATESTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP 
);


CREATE OR REPLACE TRIGGER STAFF_AUDIT
  AFTER INSERT OR DELETE OR UPDATE ON STAFF
  FOR EACH ROW
BEGIN
    IF INSERTING THEN 
        INSERT INTO STAFF_AUDIT (ID,NAME,CONTACT,EMAIL,TYPE,operation,updatedTime) VALUES (:NEW.ID,:NEW.NAME,:NEW.CONTACT,:NEW.EMAIL,:NEW.TYPE,'INSERT',SYSDATE);
    ELSIF UPDATING THEN  
        INSERT INTO STAFF_AUDIT (ID,NAME,CONTACT,EMAIL,TYPE,operation,updatedTime) VALUES (:NEW.ID,:NEW.NAME,:NEW.CONTACT,:NEW.EMAIL,:NEW.TYPE,'UPDATE',SYSDATE);
    ELSIF DELETING THEN
        INSERT INTO STAFF_AUDIT (ID,NAME,CONTACT,EMAIL,TYPE,operation,updatedTime) VALUES (:NEW.ID,:NEW.NAME,:NEW.CONTACT,:NEW.EMAIL,:NEW.TYPE,'DELETE',SYSDATE);
    END IF;
END;
